### ISSUE TITLE
Continuous Internal Next Releases

### ISSUE THREAD

**Issue by swissarmykirpan** [shabados/mobile#6]
## User Story

As a registered test user, I'd like to install and update the app easily, so that I can test and provide app feedback.

### AC1
**Given** an unregistered test user
**When** they are added to the internal test distribution group on app center
**Then** they can download next releases for iOS or Android

### AC2
**Given** a registered user with the app downloaded
**When** an native update is pushed out
**Then** the user receives an email to download the latest app
**And** the user receives a clickable push notification (from either the app or testflight) about the update

### AC3
**Given** a developer has merged a change into the trunk
**When** the CI pipeline has passed
**Then** the iOS and Android builds should be released to the test distribution group on App Center

## Approaches

> ### ❌ Approach 1 (Fastlane + App Center + Codepush) [Ad-hoc, limited]
> - Build with Fastlane in CI
> - Create a release in App Center using Fastlane in CI
> - [Create a release in App Center CodePush using CI (Fastlane?)]
> 
> **Pros:** Instant, no-review releases (until App Store actual release); No TestFlight App required; No App Expiry;
> **Cons:** Limited to 100 devices on Apple account with 1 year period for changes;

### ✅ Approach 2 (Fastlane + [Testflight & Google Play] + Codepush) <-- we're going with this!
- Build with Fastlane in CI
- Create a release in Testflight using Fastlane in CI
- Distribute release in Testfight to internal testers & general testers (primarily for app review feedback)
- Create a release in Google Play using Fastlane in CI
- Distribute release to Google Play testers
- [Push to MS App Center Codepush in CI]

**Pros:** Unlimited users on group, email-address based user-management; Earlier reviews
**Cons:** Manage distribution groups in both Google Play and Testflight; App Build expires after 90 days; Additional tool in stack (MS)

> ### ❌ Approach 3 (Fastlane + [Testflight & Google Play] + Expo-update)
> - Build with Fastlane in CI
> - Create a release in Testflight using Fastlane in CI
> - Create a release in Google Play using Fastlane in CI
> - [Push to somewhere with expo-update??]
> 
> **Pros:* No need to add/manage MS App Center;
> **Cons:** More complexity??

### Sub-tasks

- [x] Add users to App Store Connect
- [x] Create Google Play Account
- [x] Add users to Google Play
- [x] #154
- [x] #155

## Questions

- Does App Center make user group distribution unified? Or do we still have to add users to the respective distribution platforms?
- Do we care about waiting for an app center review for internal release? Nope, we have codepush and shouldn't be too bad -> no need for ad-hoc. Sounds like preferably we'd want a way of adding user email addresses in one place that'd in either internal distribution groups (to help with registering device UUIDs for no-review releases) and mainly adding email addresses for all testers (review-releases).
- [Does expo-updates give us anything over codepush? Is it the same implementation effort?]
- [ ] ** Certificate signing?? Can we avoid dealing with this ourselves entirely?** Might need an additional task here

## Notes??

- TestFlight has the superior UX over App Center vs CodePush

## Agreements

- We only would distribute next releases to non-SOS team for the sake of preview, once app is out, they'd not need the next releases -> let's optimise for the SOS team's perspective/ease
- Next releases are primarily for UAT'ing
- CodePush will **not** be covered in this ticket - it is covered in #13 

## Blocked By

- #146 
- #160

**Comment by Harjot1Singh** [comment]
FastLane + TestFlight?

**Comment by swissarmykirpan** [comment]
FastLane + AppCentre most likely, with CodePush. I think for internal builds that’s completely fine. When we get to alphas and betas, then we can go out to TestFlight

**Comment by Harjot1Singh** [comment]
iOS releases fail on next version tags - need to resolve
