### ISSUE TITLE
[Meta] Create mockups

### ISSUE THREAD

**Issue by saihaj** [shabados/mobile#74]
I would like to have an end to end mockup of how v1 should look because it will help in development process

**Comment by bhajneet** [comment]
This issue is too broad and can't be completed in short blocks of time

Can you please specify or convert this into a meta issue?

**Comment by saihaj** [comment]
* [ ] Settings menu 
* [ ] Bani/Nitnem reader mode 
* [ ] Sehaj Paath view
* [ ] Hukamnama view
* [ ] Mobile casting/ projector view 
* [ ] Read along view 
* [ ] Mobile corrections
* [ ] group paath view 

These are the few that I think are needed (from the list of features provided in meeting) because it is unclear at the moment where they go or how they are suppose to look. So please make a mock-up that will show all these features how they are planned (so we can discuss any changes before making an app)

**Comment by bhajneet** [comment]
These are all redundant, or too far in the future to consider now

Can re-open when closer
