### ISSUE TITLE
Mockup for sehaj path view 

### ISSUE THREAD

**Issue by saihaj** [shabados/mobile#77]
* [ ] Similar to reader mode #76 
* [ ] How to display user stats #54
* [ ] How can user open settings to change colors or something #75 
Related to #74

**Comment by bhajneet** [comment]
What is sehaj paath view vs reader mode view?
